In [9]:
import numpy as np

In [11]:
# Create arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Print arrays
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [10]:
# Mean, Median, and Standard Deviation
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_dev_value = np.std(array_1d)


# Basic operations
array_sum = array_1d + 10
array_product = array_1d * 2
matrix_sum = array_2d + np.array([[1, 1, 1], [1, 1, 1]])

print("Array after adding 10:", array_sum)
print("Array after multiplying by 2:", array_product)
print("Matrix after addition:\n", matrix_sum)


print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev_value)

Array after adding 10: [11 12 13 14 15]
Array after multiplying by 2: [ 2  4  6  8 10]
Matrix after addition:
 [[2 3 4]
 [5 6 7]]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
