In [1]:
import numpy as np

In [2]:
np.arange(5) / np.arange(1, 6)
# [0,1,2,3,4] / [1,2,3,4,5]  

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [3]:
x = np.arange(9).reshape((3, 3))
2 ** x
# 2 ** x raises 2 to the power of each element in 
# 2 ** 0 , 2 ** 1,2 ** 2 .......2 ** 8   

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [4]:
x = np.arange(4) 
# i.e x = [0 , 1, 2, 3]
print("x =", x)
print("x + 2 =", x + 2)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division removes decimal
print("-x = ",-x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 2 = [2 3 4 5]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [5]:
np.add(x, 2)
# + np.add Addition (e.g., 1 + 1 = 2)
# - np.subtract Subtraction (e.g., 3 - 2 = 1)
# - np.negative Unary negation (e.g., -2)
# * np.multiply Multiplication (e.g., 2 * 3 = 6)
# / np.divide Division (e.g., 3 / 2 = 1.5)
# // np.floor_divide Floor division (e.g., 3 // 2 = 1)
# ** np.power Exponentiation (e.g., 2 ** 3 = 8)
# % np.mod Modulus/remainder (e.g., 9 % 4 = 1)

array([2, 3, 4, 5])

In [6]:
x = np.array([-2,-1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [7]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [8]:
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])

# 1. For (3 - 4j): sqrt(3^2 + (-4)^2) = sqrt(9 + 16) = sqrt(25) = 5
# 2. For (4 - 3j): sqrt(4^2 + (-3)^2) = sqrt(16 + 9) = sqrt(25) = 5
# 3. For (2 + 0j): sqrt(2^2 + 0^2) = sqrt(4) = 2
# 4. For (0 + 1j): sqrt(0^2 + 1^2) = sqrt(1) = 1  

np.abs(x)

array([2, 1, 0, 1, 2])

In [9]:
theta = np.linspace(0, 5, 7)
#  theta = np.linspace(0, np.pi, 3)

In [10]:
print("theta = ", theta)
# #linspace generates  equally spaced values between 0 and 5
# # suppose np.linspace(0,5,7)
# # Due to (0,5)here array will start from 0 and end with 5 and 
# # since 5/7=0.83 the consecutive values will have ad difference of 0.83
print("sin(theta) = ", np.sin(theta))

print("cos(theta) = ", np.cos(theta))

print("tan(theta) = ", np.tan(theta))

theta =  [0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]
sin(theta) =  [ 0.          0.74017685  0.99540796  0.59847214 -0.19056796 -0.85475261
 -0.95892427]
cos(theta) =  [ 1.          0.67241224 -0.09572355 -0.80114362 -0.981674   -0.51903563
  0.28366219]
tan(theta) =  [  0.           1.10077837 -10.39877834  -0.7470223    0.19412551
   1.64680913  -3.38051501]


In [11]:
# The values are computed to within machine precision, which is why values that
# should be zero do not always hit exactly zero. Inverse trigonometric functions are also
# available
# If you have the sine of an angle and you want to retrieve the angle, np.arcsin() is the function you would use.
angles = np.arcsin([0, 0.5, 1])
print(angles)


[0.         0.52359878 1.57079633]


In [12]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [13]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [14]:
x = [1, 2, 4, 10]
# The inverse of the exponentials, the logarithms, are also available. The basic np.log
# gives the natural logarithm; if you prefer to compute the base-2 logarithm or the
# base-10 logarithm, these are available as well:
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [15]:
x = [0, 0.001, 0.01, 0.1]
# There are also some specialized versions that are useful for maintaining precision
# with very small input:
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [16]:
from scipy import special

In [17]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [18]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [22]:
x = np.arange(5) # np.arrange creates  array([0, 1, 2, 3, 4])
y = np.empty(5) #Array with 5 empty spaces
np.multiply(x, 12, out=y) #12 will be multiplied with array([0, 1, 2, 3, 4]) and output will be stored in array y with 5 empty spaces 
print(y)

[ 0. 12. 24. 36. 48.]
