In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 4, 2, 1])

In [3]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  4  2  1 99 99 99]


In [4]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])

In [6]:
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])

In [10]:
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [11]:
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])