In [8]:
import numpy as np

In [9]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [10]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [11]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [12]:
x1 # One-dimensional array

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[0]


np.int64(4)

In [15]:
x1[4]


np.int64(7)

In [16]:
x1[-1]


np.int64(9)

In [17]:
x1[-2]


np.int64(7)

In [18]:
x2# Two-dimensional array


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [19]:
x2[0, 0]


np.int64(12)

In [20]:
x2[2, 0]


np.int64(1)

In [21]:
x2[2, -1]


np.int64(7)

In [30]:
x2[0, 0] = 12
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [29]:
x1[0] = 4.14159 # 0th digit will be taken as 4
x1

array([4, 0, 3, 3, 7, 9])

In [28]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])