In [3]:
import numpy as np

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Create a 3x5  3 rows  and 5 columns
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))


array([[0.77833431, 0.68193669, 0.48954069],
       [0.920033  , 0.09113667, 0.75873947],
       [0.44198406, 0.63457859, 0.48516448]])

In [10]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
# Standard Deviation: Think of it as a measure of how much the numbers vary or spread out from the average (mean).
# In this case: A standard deviation of 1 means that most of the numbers you generate will be close to 0 (the mean).
# Specifically: About 68% of the numbers will fall between -1 and 1. 

np.random.normal(0, 1, (3, 3))


array([[-0.17782085,  0.1331962 ,  1.88383363],
       [-0.24440388, -2.18842304, -2.61333074],
       [ 0.21894372, -1.16963861,  1.52172363]])

In [11]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 0, 1],
       [5, 7, 8],
       [3, 7, 5]])

In [12]:
# Create a 3x3 identity matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])