In [18]:
import numpy as np

In [17]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:", array_1d)

# Reshaping a 2D array into a 1D array
# Creating a 2D array (matrix)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [19]:
# Accessing elements
print("First element of 1D array:", array_1d[0])
print("First row of 2D array:", array_2d[0])


# 2D Array:   [[1 2 3] [4 5 6]]

#Here 0:1 range is of row and 1:3 range is of column so the 0th row of array_2d is [1,2,3] 
#and the 1st column of 0th row is 2 and the 2nd column of 0th row is 3 thus output is [2,3]
print("Slicing 2D array:\n", array_2d[0:1, 1:3])

First element of 1D array: 1
First row of 2D array: [1 2 3]
Slicing 2D array:
 [[2 3]]
