In [3]:
import numpy as np

In [6]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1D Array:", array_1d)

# Reshaping a 2D array into a 1D array
# Creating a 2D array (matrix)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# Accessing elements
print("First element of 1D array:", array_1d[0])
print("First row of 2D array:", array_2d[0])
print("Slicing 2D array:\n", array_2d[0:1, 1:3])

First element of 1D array: 1
First row of 2D array: [1 2 3]
Slicing 2D array:
 [[2 3]]
