In [90]:
import numpy as np

In [91]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print("1D Array:", array_1d)

# Creating a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [92]:
# Reshaping a 1D array into a 2D array
reshaped_array = array_1d.reshape(5,2)
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [93]:
# Mean, Median, and Standard Deviation
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_dev_value = np.std(array_1d)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev_value)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [94]:
# Accessing elements
print("First element of 1D array:", array_1d[0])
print("First row of 2D array:", array_2d[0])
print("Slicing 2D array:\n", array_2d[0:1, 1:3])

First element of 1D array: 1
First row of 2D array: [1 2 3]
Slicing 2D array:
 [[2 3]]


In [95]:
import numpy as np

# Create arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Print arrays
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)

# Basic operations
array_sum = array_1d + 10
array_product = array_1d * 2
matrix_sum = array_2d + np.array([[1, 1, 1], [1, 1, 1]])

print("Array after adding 10:", array_sum)
print("Array after multiplying by 2:", array_product)
print("Matrix after addition:\n", matrix_sum)

# Reshape and statistical operations
reshaped_array = array_1d.reshape(5, 1)
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_dev_value = np.std(array_1d)

print("Reshaped Array:\n", reshaped_array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev_value)

# Indexing and slicing
print("First element of 1D array:", array_1d[0])
print("First row of 2D array:", array_2d[0])
print("Slicing 2D array:\n", array_2d[0:1, 1:3])

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array after adding 10: [11 12 13 14 15]
Array after multiplying by 2: [ 2  4  6  8 10]
Matrix after addition:
 [[2 3 4]
 [5 6 7]]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
First element of 1D array: 1
First row of 2D array: [1 2 3]
Slicing 2D array:
 [[2 3]]
